import React, { useState } from 'react';
import { PipelineCanvas } from './PipelineCanvas';
import { useWorkflowStore } from '../../stores/workflowStore';
import { useClaimsStore } from '../../stores/claimsStore';

export function PipelineTab() {
  const { isExecuting, resetExecution, executeAll } = useWorkflowStore();
  const { currentClaim } = useClaimsStore();
  const [showInfo, setShowInfo] = useState(false);

  return (
    <div className="w-full h-full flex flex-col relative overflow-hidden">
      <div className="h-[44px] border-b-[0.5px] border-border bg-surface px-[16px] flex items-center gap-[8px] shrink-0">
        <button className="h-[28px] px-[12px] border-[0.5px] border-border-strong bg-elevated text-text-secondary rounded-[4px] font-mono text-[11px] hover:text-text-primary hover:border-border-active transition-colors">
          + Add Node
        </button>
        <button className="h-[28px] px-[12px] border-[0.5px] border-border-strong bg-elevated text-text-secondary rounded-[4px] font-mono text-[11px] hover:text-text-primary hover:border-border-active transition-colors">
          Export JSON
        </button>
        <button className="h-[28px] px-[12px] border-[0.5px] border-border-strong bg-elevated text-text-secondary rounded-[4px] font-mono text-[11px] hover:text-text-primary hover:border-border-active transition-colors">
          Import JSON
        </button>
        <button 
          onClick={resetExecution}
          className="h-[28px] px-[12px] border-[0.5px] border-border-strong bg-elevated text-text-secondary rounded-[4px] font-mono text-[11px] hover:text-text-primary hover:border-border-active transition-colors"
        >
          Reset
        </button>
        
        {/* Info button */}
        <button
          onClick={() => setShowInfo(!showInfo)}
          className="ml-auto h-[28px] w-[28px] border-[0.5px] border-border-strong bg-elevated text-text-secondary rounded-[4px] font-mono text-[11px] hover:text-amber hover:border-amber transition-colors"
          title="What does Execute do?"
        >
          ?
        </button>

        <button
          disabled={isExecuting || !currentClaim}
          onClick={() => currentClaim && executeAll(currentClaim)}
          className="h-[28px] px-[12px] bg-amber text-[#080808] border-none rounded-[4px] font-display font-semibold text-[11px] cursor-pointer hover:brightness-105 transition-all disabled:opacity-50 flex items-center gap-2"
        >
          {isExecuting ? (
            <>
              <div className="spin-ring scale-[0.6] origin-center -ml-1 border-bg" />
              <span>Executing...</span>
            </>
          ) : (
            <span>▶ Execute</span>
          )}
        </button>
      </div>

      {showInfo && (
        <div className="mx-4 mt-3 bg-elevated border border-amber/30 rounded-[6px] p-4 font-mono text-[11px] text-text-secondary flex flex-col gap-2 animate-fade-in-up">
          <div className="text-amber font-semibold text-[12px] mb-1">What does ▶ Execute do?</div>
          <p>Execute runs your current claim through the pipeline nodes generated by the AI council, step by step:</p>
          <ol className="flex flex-col gap-1 pl-3">
            {[
              ['Intake', 'Parses claim ID, policy type, amount, document status, and image URL.'],
              ['Coverage Check', 'Validates whether the policy type covers the claimed damage.'],
              ['Fraud Detection', 'Scores fraud risk using past claims count, document gaps, and amount vs. damage.'],
              ['Vision AI', 'If an image is provided, the vision model analyzes damage severity and checks consistency with the description.'],
              ['Decision Gate', 'Branches to Approved / Pending / Rejected based on coverage and fraud results.'],
              ['Payout Engine', 'Applies the damage-severity payout percentage (Minor 70–90%, Moderate 50–70%, Major 30–50%) minus the ₹3,000 deductible.'],
              ['Confidence Score', 'Computes a 0–100% confidence band (High / Medium / Low) based on data completeness and risk flags.'],
              ['Communication', 'Generates a polite, accurate customer-facing message for the decision.'],
              ['Output', 'Compiles the final status, estimated payout, confidence, and reason into a single result.'],
            ].map(([node, desc]) => (
              <li key={node} className="flex gap-2">
                <span className="text-amber shrink-0">{node}:</span>
                <span>{desc}</span>
              </li>
            ))}
          </ol>
          <p className="text-text-muted text-[10px] mt-1">Each node uses the decision already computed by the AI council — no extra LLM calls are made during pipeline execution.</p>
          <button onClick={() => setShowInfo(false)} className="text-amber text-[10px] self-end hover:text-amber-bright">Close ×</button>
        </div>
      )}

      <div className="flex-1 relative bg-bg panel-texture">
         <PipelineCanvas />
      </div>
    </div>
  );
}
